services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cartservice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: